name = "y3y_luau/krissh_wtf"
version = "0.1.0"
description = "Hide text in plain sight, using invisible characters! now in Luau"
authors = ["krissh-wtf"]
repository = "https://github.com/krissh-wtf/y3y-luau"
license = "MIT"

[target]
environment = "luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
